# Generated by Django 5.2.1 on 2025-05-22 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_usersubscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 22, 21, 8, 44, 24276, tzinfo=datetime.timezone.utc)),
        ),
    ]
