# Generated by Django 5.1.6 on 2025-05-07 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, unique=True)),
                ('species', models.IntegerField(choices=[(1, 'Cattle'), (2, 'Poultry'), (3, 'Pig'), (4, 'Sheep'), (5, 'Goat'), (99, 'Other')], default=99)),
                ('purchase_date', models.DateField()),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Mixed')], default=3)),
                ('quantity', models.PositiveIntegerField()),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=100, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('health_status', models.IntegerField(choices=[(1, 'Healthy'), (2, 'Sick'), (3, 'Recovering'), (4, 'Dead')], default=1)),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Mixed')], editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='farm.animalbatch')),
            ],
        ),
    ]
