# Generated by Django 5.1.6 on 2025-05-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='animalbatch',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
