# Generated by Django 5.1.6 on 2025-05-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_animal_slug_alter_animalbatch_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('illness', 'Illness'), ('treatment', 'Treatment'), ('checkup', 'Checkup'), ('vaccine', 'Vaccine'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('veterinarian', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='farm.animal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
