# Generated by Django 5.1.6 on 2025-05-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_healthevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthevent',
            name='date',
            field=models.DateField(),
        ),
    ]
