# Generated by Django 5.1.6 on 2025-05-11 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_healthevent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_type', models.CharField(choices=[('MEAT', 'Carne'), ('MILK', 'Leche'), ('EGG', 'Huevos'), ('WOOL', 'Lana')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('L', 'Litros'), ('KG', 'Kilogramos'), ('U', 'Unidades')], max_length=2)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='farm.animalbatch')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
