# Generated by Django 5.1.6 on 2025-05-12 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FEED', 'Alimento'), ('VET', 'Veterinaria'), ('MAINTENANCE', 'Mantenimiento'), ('LABOR', 'Mano de obra'), ('EQUIPMENT', 'Equipamiento'), ('OTHER', 'Otro')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('€', 'Euros'), ('$', 'Dollars'), ('', 'Other')], default='€', max_length=5)),
                ('date', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='farm.animalbatch')),
            ],
        ),
    ]
