# Generated by Django 5.1.6 on 2025-05-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_expense_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('BANK_TRANSFER', 'Transferencia Bancaria'), ('MOBILE_PAYMENT', 'Pago Móvil'), ('CHECK', 'Cheque'), ('OTHER', 'Otro')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='farm.animalbatch'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SALE', 'Venta'), ('SUBSIDY', 'Subvención'), ('DONATION', 'Donación'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('€', 'Euros'), ('$', 'Dollars'), ('', 'Other')], default='€', max_length=5)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='farm.animalbatch')),
            ],
        ),
    ]
